[package]
name = "junetag"
version = "0.1.0"
edition = "2021"
authors = ["Joseph Catrambone <jo.jcat@gmail.com>"]
publish = false
autobins = false

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
image = "~0.24"
rayon = "1.6"